### ISSUE TITLE
requests for manifest.json of UI5 libraries failing

### ISSUE THREAD

**Issue by smahati** [ui5-community/generator-ui5-app#14]
Hello,

When I generate an application with the following options:

? Select your generator? app
? Enter your application id (namespace)? luigi.ui5app
? Which framework do you want to use? OpenUI5
? Which framework version do you want to use? 1.121.1
? Who is the author of the application? Mahati
? Would you like to create a new directory for the application? No
? Would you like to initialize a local git repository for the application? No

The generated application tries to get manifest.json but the request fails: `GET http://localhost:8080/resources/sap/m/manifest.json 404 (Not Found)`.

Is this unavoidable due to how UI5 works or is there an issue that needs to be addressed in the generated app?

Best regards,
Mahati (She/Her)

**Comment by matz3** [comment]
Unfortunately, this is currently unavoidable as for most libraries, the `manifest.json` files are only generated during build. There's nothing that can be changed in the generated app or generator.

Please file an issue at https://github.com/SAP/ui5-tooling/issues in case this causes errors during development (other than just having this 404 request error).

Our plan is to make a `manifest.json` file mandatory for libraries, which would resolve the issue. This is currently listed in https://github.com/SAP/ui5-tooling/issues/701 as `Breaking change: Require a manifest.json for libraries`. However, it is not clear when this will happen. It is not planned for the upcoming major version update v4.
